version: '2.0'

volumes:
  postgres_data:
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
  djangoauth:
    build:
         context: ./DjangoAuthServer/
    command: /app/fire.sh
    environment:
       - DATABASE_PASSWORD=${DATABASE_PASSWORD}
       - DATABASE_USER=${DATABASE_USER}
       - DATABASE_NAME=${DATABASE_NAME}
       - DATABASE_HOST=${DATABASE_HOST}
       - SECRET_KEY=${SECRET_KEY}
    volumes:
    - static-content-auth:/app/static/
    - media-content-auth:/app/media/
    depends_on:
      - db

  djangoapp:
    build:
         context: ./DjangoAppServer/
    command: /app/fire.sh
    environment:
       - DATABASE_PASSWORD=${DATABASE_PASSWORD}
       - DATABASE_USER=${DATABASE_USER}
       - DATABASE_NAME=${DATABASE_NAME}
       - DATABASE_HOST=${DATABASE_HOST}
       - SECRET_KEY=${SECRET_KEY}
    volumes:
    - static-content-app:/app/static/
    - media-content-app:/app/media/
    depends_on:
      - db
  nginx:
    restart: always
    build:
         context: ./nginx/
    ports: 
      - "8080:8080"
    depends_on:
          - djangoapp
          - djangoauth
    volumes:
      - static-content-app:/app/static
      - static-content-auth:/auth/static
      - media-content-app:/app/media
      - media-content-auth:/auth/media
      - logs-app:/srv/www/djangoapp/logs


volumes:
    static-content-app:
    static-content-auth:
    media-content-app:
    media-content-auth:
    logs-app:
